// Email service for TMV Business Solutions
const nodemailer = require('nodemailer');

// Afrihost SMTP Configuration
const emailConfig = {
    host: 'mail.tmvbusinesssolutions.co.za', // or 'mail.afrihost.co.za'
    port: 587, // STARTTLS port
    secure: false, // true for 465 (SSL), false for other ports
    auth: {
        user: 'leads@tmvbusinesssolutions.co.za',
        pass: 'Tshepiso@1985'
    },
    tls: {
        ciphers: 'SSLv3'
    }
};

// Alternative configuration if the above doesn't work
const alternativeConfig = {
    host: 'smtp.afrihost.co.za',
    port: 465, // SSL port
    secure: true, // true for 465 (SSL)
    auth: {
        user: 'leads@tmvbusinesssolutions.co.za',
        pass: 'Tshepiso@1985'
    }
};

// Create transporter
const createTransporter = () => {
    try {
        return nodemailer.createTransporter(emailConfig);
    } catch (error) {
        console.log('Primary config failed, trying alternative...');
        return nodemailer.createTransporter(alternativeConfig);
    }
};

// Send registration notification
const sendRegistrationNotification = async (userData) => {
    const transporter = createTransporter();
    
    const mailOptions = {
        from: 'leads@tmvbusinesssolutions.co.za',
        to: 'leads@tmvbusinesssolutions.co.za',
        subject: '🎉 New User Registration - TMV Business Solutions',
        html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f9f9f9;">
            <div style="background-color: #007bff; color: white; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
                <h1 style="margin: 0;">🎉 New User Registration</h1>
                <p style="margin: 5px 0 0 0;">TMV Business Solutions</p>
            </div>
            
            <div style="background-color: white; padding: 30px; border-radius: 0 0 8px 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
                <h2 style="color: #333; margin-top: 0;">New User Details</h2>
                
                <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
                    <tr style="background-color: #f8f9fa;">
                        <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold;">Name:</td>
                        <td style="padding: 12px; border: 1px solid #dee2e6;">${userData.firstName} ${userData.lastName}</td>
                    </tr>
                    <tr>
                        <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold;">Email:</td>
                        <td style="padding: 12px; border: 1px solid #dee2e6;">${userData.email}</td>
                    </tr>
                    <tr style="background-color: #f8f9fa;">
                        <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold;">User Type:</td>
                        <td style="padding: 12px; border: 1px solid #dee2e6;">${userData.userType || 'Client'}</td>
                    </tr>
                    <tr>
                        <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold;">Registration Date:</td>
                        <td style="padding: 12px; border: 1px solid #dee2e6;">${new Date().toLocaleString()}</td>
                    </tr>
                </table>
                
                <div style="background-color: #e3f2fd; padding: 15px; border-radius: 5px; margin: 20px 0;">
                    <p style="margin: 0; color: #1565c0;">
                        <strong>Action Required:</strong> A new user has registered on your website. 
                        You may want to follow up with them about your services.
                    </p>
                </div>
                
                <p style="color: #666; font-size: 14px; margin-top: 30px;">
                    This email was automatically generated by the TMV Business Solutions website registration system.
                </p>
            </div>
        </div>
        `
    };

    try {
        const result = await transporter.sendMail(mailOptions);
        console.log('Registration notification sent successfully:', result.messageId);
        return { success: true, messageId: result.messageId };
    } catch (error) {
        console.error('Failed to send registration notification:', error);
        return { success: false, error: error.message };
    }
};

// Send quote request notification
const sendQuoteRequestNotification = async (quoteData) => {
    const transporter = createTransporter();
    
    const mailOptions = {
        from: 'leads@tmvbusinesssolutions.co.za',
        to: 'leads@tmvbusinesssolutions.co.za',
        subject: '💰 New Quote Request - TMV Business Solutions',
        html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f9f9f9;">
            <div style="background-color: #28a745; color: white; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
                <h1 style="margin: 0;">💰 New Quote Request</h1>
                <p style="margin: 5px 0 0 0;">TMV Business Solutions</p>
            </div>
            
            <div style="background-color: white; padding: 30px; border-radius: 0 0 8px 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
                <h2 style="color: #333; margin-top: 0;">Quote Request Details</h2>
                
                <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
                    <tr style="background-color: #f8f9fa;">
                        <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold;">Client Name:</td>
                        <td style="padding: 12px; border: 1px solid #dee2e6;">${quoteData.name}</td>
                    </tr>
                    <tr>
                        <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold;">Email:</td>
                        <td style="padding: 12px; border: 1px solid #dee2e6;">${quoteData.email}</td>
                    </tr>
                    <tr style="background-color: #f8f9fa;">
                        <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold;">Phone:</td>
                        <td style="padding: 12px; border: 1px solid #dee2e6;">${quoteData.phone || 'Not provided'}</td>
                    </tr>
                    <tr>
                        <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold;">Service:</td>
                        <td style="padding: 12px; border: 1px solid #dee2e6;">${quoteData.service}</td>
                    </tr>
                    <tr style="background-color: #f8f9fa;">
                        <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold;">Request Date:</td>
                        <td style="padding: 12px; border: 1px solid #dee2e6;">${new Date().toLocaleString()}</td>
                    </tr>
                </table>
                
                ${quoteData.message ? `
                <h3 style="color: #333; margin-top: 30px;">Additional Details:</h3>
                <div style="background-color: #f8f9fa; padding: 15px; border-radius: 5px; border-left: 4px solid #28a745;">
                    <p style="margin: 0; white-space: pre-wrap;">${quoteData.message}</p>
                </div>
                ` : ''}
                
                <div style="background-color: #fff3cd; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #ffc107;">
                    <p style="margin: 0; color: #856404;">
                        <strong>⚡ High Priority:</strong> This is a potential sales lead. Please follow up promptly!
                    </p>
                </div>
                
                <p style="color: #666; font-size: 14px; margin-top: 30px;">
                    This email was automatically generated by the TMV Business Solutions quote request system.
                </p>
            </div>
        </div>
        `
    };

    try {
        const result = await transporter.sendMail(mailOptions);
        console.log('Quote request notification sent successfully:', result.messageId);
        return { success: true, messageId: result.messageId };
    } catch (error) {
        console.error('Failed to send quote request notification:', error);
        return { success: false, error: error.message };
    }
};

// Send booking notification
const sendBookingNotification = async (bookingData) => {
    const transporter = createTransporter();
    
    const mailOptions = {
        from: 'leads@tmvbusinesssolutions.co.za',
        to: 'leads@tmvbusinesssolutions.co.za',
        subject: '📅 New Service Booking - TMV Business Solutions',
        html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f9f9f9;">
            <div style="background-color: #dc3545; color: white; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
                <h1 style="margin: 0;">📅 New Service Booking</h1>
                <p style="margin: 5px 0 0 0;">TMV Business Solutions</p>
            </div>
            
            <div style="background-color: white; padding: 30px; border-radius: 0 0 8px 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
                <h2 style="color: #333; margin-top: 0;">Booking Details</h2>
                
                <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
                    <tr style="background-color: #f8f9fa;">
                        <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold;">Client Name:</td>
                        <td style="padding: 12px; border: 1px solid #dee2e6;">${bookingData.name}</td>
                    </tr>
                    <tr>
                        <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold;">Email:</td>
                        <td style="padding: 12px; border: 1px solid #dee2e6;">${bookingData.email}</td>
                    </tr>
                    <tr style="background-color: #f8f9fa;">
                        <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold;">Phone:</td>
                        <td style="padding: 12px; border: 1px solid #dee2e6;">${bookingData.phone || 'Not provided'}</td>
                    </tr>
                    <tr>
                        <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold;">Service:</td>
                        <td style="padding: 12px; border: 1px solid #dee2e6;">${bookingData.service}</td>
                    </tr>
                    <tr style="background-color: #f8f9fa;">
                        <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold;">Preferred Date:</td>
                        <td style="padding: 12px; border: 1px solid #dee2e6;">${bookingData.preferredDate || 'ASAP'}</td>
                    </tr>
                    <tr>
                        <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold;">Booking Date:</td>
                        <td style="padding: 12px; border: 1px solid #dee2e6;">${new Date().toLocaleString()}</td>
                    </tr>
                </table>
                
                ${bookingData.requirements ? `
                <h3 style="color: #333; margin-top: 30px;">Special Requirements:</h3>
                <div style="background-color: #f8f9fa; padding: 15px; border-radius: 5px; border-left: 4px solid #dc3545;">
                    <p style="margin: 0; white-space: pre-wrap;">${bookingData.requirements}</p>
                </div>
                ` : ''}
                
                <div style="background-color: #f8d7da; padding: 15px; border-radius: 5px; margin: 20px 0; border-left: 4px solid #dc3545;">
                    <p style="margin: 0; color: #721c24;">
                        <strong>🚨 Urgent:</strong> This is a confirmed booking. Please contact the client immediately to confirm details and schedule!
                    </p>
                </div>
                
                <p style="color: #666; font-size: 14px; margin-top: 30px;">
                    This email was automatically generated by the TMV Business Solutions booking system.
                </p>
            </div>
        </div>
        `
    };

    try {
        const result = await transporter.sendMail(mailOptions);
        console.log('Booking notification sent successfully:', result.messageId);
        return { success: true, messageId: result.messageId };
    } catch (error) {
        console.error('Failed to send booking notification:', error);
        return { success: false, error: error.message };
    }
};

// Test email configuration
const testEmailConfiguration = async () => {
    const transporter = createTransporter();
    
    try {
        await transporter.verify();
        console.log('✅ Email configuration is valid and ready to send emails');
        return { success: true, message: 'Email configuration verified' };
    } catch (error) {
        console.error('❌ Email configuration failed:', error);
        return { success: false, error: error.message };
    }
};

// Send job application notification
const sendJobApplicationNotification = async (applicationData) => {
    const transporter = createTransporter();
    
    const { jobId, jobTitle, jobType, company, location, applicant, profile } = applicationData;
    
    // Use the actual job title passed from the server, or fallback
    const displayJobTitle = jobTitle || `Job ID: ${jobId}`;
    const displayCompany = company || 'TMV Business Solutions';
    const displayLocation = location || 'South Africa';
    
    const mailOptions = {
        from: 'leads@tmvbusinesssolutions.co.za',
        to: 'careers@tmvbusinesssolutions.co.za',
        subject: `📋 New Job Application - ${applicant.firstName} ${applicant.lastName} for ${displayJobTitle}`,
        html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f9f9f9;">
            <div style="background-color: #1e40af; color: white; padding: 20px; text-align: center; border-radius: 8px 8px 0 0;">
                <h1 style="margin: 0;">📋 New Job Application</h1>
                <p style="margin: 5px 0 0 0;">TMV Business Solutions</p>
            </div>
            
            <div style="background-color: white; padding: 30px; border-radius: 0 0 8px 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1);">
                <h2 style="color: #333; margin-top: 0;">Application for: ${displayJobTitle}</h2>
                <p style="color: #666; margin: 5px 0 20px 0;">
                    <strong>Company:</strong> ${displayCompany}<br>
                    <strong>Location:</strong> ${displayLocation}<br>
                    ${jobType ? `<strong>Job Type:</strong> ${jobType}<br>` : ''}
                </p>
                
                <h3 style="color: #1e40af; border-bottom: 2px solid #1e40af; padding-bottom: 5px;">Applicant Information</h3>
                <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
                    <tr style="background-color: #f8f9fa;">
                        <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold;">Full Name:</td>
                        <td style="padding: 12px; border: 1px solid #dee2e6;">${applicant.firstName} ${applicant.lastName}</td>
                    </tr>
                    <tr>
                        <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold;">Email:</td>
                        <td style="padding: 12px; border: 1px solid #dee2e6;">${applicant.email}</td>
                    </tr>
                    <tr style="background-color: #f8f9fa;">
                        <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold;">Phone:</td>
                        <td style="padding: 12px; border: 1px solid #dee2e6;">${applicant.phone}</td>
                    </tr>
                    <tr>
                        <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold;">ID Number:</td>
                        <td style="padding: 12px; border: 1px solid #dee2e6;">${applicant.idNumber}</td>
                    </tr>
                    ${profile.gender ? `
                    <tr style="background-color: #f8f9fa;">
                        <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold;">Gender:</td>
                        <td style="padding: 12px; border: 1px solid #dee2e6;">${profile.gender}</td>
                    </tr>
                    ` : ''}
                    ${profile.province ? `
                    <tr>
                        <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold;">Location:</td>
                        <td style="padding: 12px; border: 1px solid #dee2e6;">${profile.suburb || ''}, ${profile.town || ''}, ${profile.province}</td>
                    </tr>
                    ` : ''}
                    <tr style="background-color: #f8f9fa;">
                        <td style="padding: 12px; border: 1px solid #dee2e6; font-weight: bold;">Application Date:</td>
                        <td style="padding: 12px; border: 1px solid #dee2e6;">${new Date().toLocaleString()}</td>
                    </tr>
                </table>
                
                ${profile.qualifications && profile.qualifications.length > 0 ? `
                <h3 style="color: #1e40af; border-bottom: 2px solid #1e40af; padding-bottom: 5px;">Qualifications</h3>
                <ul style="list-style-type: none; padding: 0;">
                    ${profile.qualifications.map(q => `
                        <li style="background-color: #f8f9fa; padding: 10px; margin: 5px 0; border-left: 3px solid #1e40af;">
                            <strong>${q.level}</strong> from ${q.institute} (${q.date})
                        </li>
                    `).join('')}
                </ul>
                ` : ''}
                
                <div style="background-color: #dbeafe; padding: 15px; border-radius: 5px; margin: 20px 0;">
                    <p style="margin: 0; color: #1e40af;">
                        <strong>Action Required:</strong> Review the applicant's profile in the jobseeker portal and contact them if they match the job requirements.
                    </p>
                </div>
                
                <div style="text-align: center; margin: 30px 0;">
                    <p style="margin: 0; color: #666; font-size: 14px;">
                        To view the full applicant profile with documents and photos, log in to the admin portal.
                    </p>
                </div>
                
                <p style="color: #666; font-size: 14px; margin-top: 30px;">
                    This email was automatically generated by the TMV Business Solutions job application system.
                </p>
            </div>
        </div>
        `
    };

    try {
        const result = await transporter.sendMail(mailOptions);
        console.log('Job application notification sent successfully:', result.messageId);
        return { success: true, messageId: result.messageId };
    } catch (error) {
        console.error('Failed to send job application notification:', error);
        return { success: false, error: error.message };
    }
};

module.exports = {
    sendRegistrationNotification,
    sendQuoteRequestNotification,
    sendBookingNotification,
    sendJobApplicationNotification,
    testEmailConfiguration
};